- become: yes
  hosts: all
  name: browsertrix-provision
  roles:
    - role: upgrade
    - role: docker
    - role: aws-cli
    - role: user
    - role: tmux-conky

  tasks:
    - name: Pull the browsertrix Docker image
      docker_image:
        name: webrecorder/browsertrix-crawler
        source: pull
