- name: Install aptitude using apt # this is preferred by ansible
  apt: 
    name: aptitude
    state: latest
    update_cache: yes
    force_apt_get: yes
    lock_timeout: 120

- name: Upgrade apt packages
  apt:
    upgrade: safe
    lock_timeout: 120
