- name: Wait for apt to unlock
  shell: while fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 5; done;

- name: Install aptitude using apt # this is preferred by ansible
  apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

- name: Wait for apt to unlock
  shell: while fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 5; done;

- name: Upgrade apt packages
  apt:
    upgrade: safe
