- name: Create the "docker" group
  group:
    name: docker
    state: present

- name: Install required system packages
  apt:
    name: "{{ item }}"
    state: latest
    lock_timeout: 120
  loop:
    [
      "apt-transport-https",
      "ca-certificates",
      "python3-pip",
      "python3-setuptools",
      "software-properties-common",
    ]

- name: Fetch and add the Docker GPG apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Update apt cache and install docker-ce
  apt:
    name: docker-ce
    state: latest
    lock_timeout: 120

- name: Install Docker Module for Python
  pip:
    name: docker

- name: Install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    group: docker
    mode: 0750
